#!/bin/bash
# Script for generating a graph of the given WAV file.

file=$(basename $1 .wav)

sox $file.wav withcomments.dat
tail -n+3 withcomments.dat > $file.dat
rm withcomments.dat

cat > $file.gpi <<- EOM
set term jpeg size 800,600
set output "$file.jpeg"
set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"
set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"
plot "$file.dat" with lines lt rgb 'red'
EOM

gnuplot $file.gpi
rm $file.gpi
rm $file.dat
